// This file is autogenerated by CMake: DO NOT EDIT

#ifndef KSYNTAXHIGHLIGHTING_LOG_H
#define KSYNTAXHIGHLIGHTING_LOG_H

#include <QLoggingCategory>
 namespace KSyntaxHighlighting {
Q_DECLARE_LOGGING_CATEGORY(Log)
} 

#endif
