// This file is autogenerated by CMake: DO NOT EDIT

#include "ksyntaxhighlighting_logging.h"

 namespace KSyntaxHighlighting {
#if QT_VERSION >= QT_VERSION_CHECK(5, 4, 0)
Q_LOGGING_CATEGORY(Log, "org.kde.ksyntaxhighlighting", QtInfoMsg)
#else
Q_LOGGING_CATEGORY(Log, "org.kde.ksyntaxhighlighting")
#endif
} 
